"""Seed a believable commit history for demos — through the real pipeline.

    python -m scripts.seed_demo_data "<Vehicle name>" [--author "Name"] [--set-stages]

Creates the vehicle's folder layout, then commits one or two small sample files
per subsystem exactly as an engineer would: uploaded to real Box, hashed, and
anchored to XRPL Testnet (synchronously, so the output shows each transaction).
Nothing is faked or backdated — timestamps are real, so run this a few days
before a demo, or re-run it (with --force) to add more history over time.

Every sample file says in its first line that it is demo data, so it's easy to
find and delete from Box afterwards. `--set-stages` also fills in a design stage
for subsystems that don't have one yet; leads are never invented.
"""

from __future__ import annotations

import argparse
from collections.abc import Callable
from dataclasses import dataclass

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.config import get_settings
from app.db import get_sessionmaker, run_migrations
from app.models import CdxCommit, SubsystemMetadata, SubsystemStage
from app.schemas.auth import SessionUser
from app.schemas.dashboard import SubsystemUpdate
from app.services.anchoring import anchor_cdx_commit
from app.services.box_client import BoxService, get_box_service
from app.services.cdx_commits import CommitFile, create_cdx_commit
from app.services.dashboard import update_subsystem
from app.services.folder_layout import ensure_vehicle_layout
from app.services.xrpl_client import XrplClient, get_xrpl_client

DEMO_HEADER = "Sample data generated by the CDX demo seed script (scripts/seed_demo_data.py)."


def _csv(header: str, rows: list[tuple]) -> bytes:
    lines = [f"# {DEMO_HEADER}", header, *(",".join(str(v) for v in row) for row in rows)]
    return ("\n".join(lines) + "\n").encode()


def _markdown(title: str, *paragraphs: str) -> bytes:
    return "\n\n".join([f"<!-- {DEMO_HEADER} -->", f"# {title}", *paragraphs, ""]).encode()


@dataclass(frozen=True)
class DemoCommit:
    subsystem: str
    in_cad_folder: bool
    file_name: str
    message: str
    content: bytes
    design_review: tuple[str, bytes] | None = None


DEMO_COMMITS: tuple[DemoCommit, ...] = (
    DemoCommit(
        "battery",
        False,
        "pack-thermal-test.csv",
        "Thermal test: 2C discharge at 25 °C ambient, hottest cell stayed under 45 °C",
        _csv(
            "minute,pack_current_a,max_cell_temp_c,min_cell_voltage_v",
            [
                (m, 38.0, round(25 + m * 0.62, 1), round(4.15 - m * 0.021, 3))
                for m in range(0, 31, 3)
            ],
        ),
        (
            "pack-layout-review.md",
            _markdown(
                "Pack layout design review",
                "Attendees: battery, electrical, chassis leads.",
                "Decision: move cell tabs 2 mm inboard to clear the enclosure lid fasteners.",
                "Follow-up: re-run the thermal test at 2C after the change.",
            ),
        ),
    ),
    DemoCommit(
        "chassis",
        True,
        "rear-subframe-bom.csv",
        "Rear subframe BOM after moving to 1 in × 0.049 in 4130 tube",
        _csv(
            "part,material,qty,length_mm",
            [
                ("upper rail", "4130 1in x 0.049in", 2, 812),
                ("lower rail", "4130 1in x 0.049in", 2, 790),
                ("cross member", "4130 0.75in x 0.035in", 3, 540),
                ("gusset", "4130 sheet 0.063in", 8, 0),
            ],
        ),
    ),
    DemoCommit(
        "dynamics",
        False,
        "front-suspension-hardpoints.csv",
        "Front hardpoints after bump-steer study (toe change now < 0.1° over travel)",
        _csv(
            "point,x_mm,y_mm,z_mm",
            [
                ("upper_a_arm_front", 102.0, 285.5, 410.0),
                ("upper_a_arm_rear", -98.0, 290.0, 405.0),
                ("lower_a_arm_front", 110.0, 250.0, 180.0),
                ("lower_a_arm_rear", -112.0, 252.0, 176.0),
                ("tie_rod_inner", -60.0, 240.0, 230.0),
                ("tie_rod_outer", -68.0, 560.0, 228.0),
            ],
        ),
        (
            "suspension-geometry-review.md",
            _markdown(
                "Front suspension geometry review",
                "Bump steer reduced by raising the inner tie-rod point 4 mm.",
                "Open question for chassis: clearance to the steering rack mount.",
            ),
        ),
    ),
    DemoCommit(
        "electrical",
        True,
        "bms-harness-pinout.csv",
        "BMS harness pinout rev C: sense lines rerouted away from the motor controller",
        _csv(
            "connector,pin,signal,wire_gauge_awg",
            [("J1", pin, f"CELL_{pin:02d}_SENSE", 22) for pin in range(1, 13)],
        ),
    ),
    DemoCommit(
        "shell",
        False,
        "nose-cone-layup-schedule.md",
        "Nose cone layup schedule: 3 plies 2x2 twill around 6 mm foam core",
        _markdown(
            "Nose cone layup schedule",
            "1. Mold release (3 coats), tack cloth between coats.",
            "2. Ply 1–2: 2x2 twill carbon, 0°/45°.",
            "3. 6 mm foam core, scored at the curvature transition.",
            "4. Ply 3: 2x2 twill carbon, 0°. Vacuum bag at −0.9 bar for 12 h.",
        ),
    ),
    DemoCommit(
        "solar",
        True,
        "array-string-layout.csv",
        "Array string layout: 4 strings × 60 cells, bypass diodes every 12 cells",
        _csv("string,cells,bypass_diodes,mppt_channel", [(s, 60, 5, s) for s in range(1, 5)]),
    ),
    DemoCommit(
        "strategy",
        False,
        "day-1-energy-model.csv",
        "Day 1 energy model: target 62 km/h average holds 20% state of charge at arrival",
        _csv(
            "segment,distance_km,target_speed_kmh,expected_soc_pct",
            [(1, 48, 64, 88), (2, 61, 60, 71), (3, 55, 63, 52), (4, 70, 61, 31), (5, 42, 62, 20)],
        ),
    ),
    DemoCommit(
        "bizops",
        False,
        "sponsor-update-outline.md",
        "Outline for the fall sponsor update",
        _markdown(
            "Fall sponsor update — outline",
            "1. Season goals and timeline.",
            "2. Subsystem progress (pull stages from the CDX dashboard).",
            "3. How sponsor support is being used.",
        ),
    ),
)

# Applied with --set-stages, and only to subsystems that have no stage yet.
DEMO_STAGES: dict[str, SubsystemStage] = {
    "battery": SubsystemStage.TESTING,
    "chassis": SubsystemStage.MANUFACTURING,
    "dynamics": SubsystemStage.REVIEW,
    "electrical": SubsystemStage.DESIGN,
    "shell": SubsystemStage.MANUFACTURING,
    "solar": SubsystemStage.TESTING,
    "strategy": SubsystemStage.DESIGN,
    "bizops": SubsystemStage.CONCEPT,
}


class DemoDataExistsError(Exception):
    pass


def seed_demo_data(
    db: Session,
    box: BoxService,
    xrpl: XrplClient,
    *,
    root_folder_id: str,
    vehicle: str,
    author: SessionUser,
    set_stages: bool = False,
    force: bool = False,
    log: Callable[[str], None] = print,
) -> list[CdxCommit]:
    if not force and db.scalar(select(func.count(CdxCommit.id))):
        raise DemoDataExistsError(
            "CDX already has commits; pass --force to add demo commits anyway"
        )

    layout = ensure_vehicle_layout(box, root_folder_id, vehicle)
    seeded = []
    for demo in DEMO_COMMITS:
        folders = layout[demo.subsystem]
        cdx_commit = create_cdx_commit(
            db,
            box,
            folder_id=folders.cad_folder_id if demo.in_cad_folder else folders.folder_id,
            file=CommitFile(demo.file_name, demo.content),
            message=demo.message,
            author=author,
            design_review=CommitFile(*demo.design_review) if demo.design_review else None,
        )
        cdx_commit = anchor_cdx_commit(db, xrpl, cdx_commit.id)
        log(
            f"{demo.subsystem:>10}  {demo.file_name:<34} {cdx_commit.anchor_status:<8} "
            f"{cdx_commit.xrpl_tx_hash or cdx_commit.anchor_error or ''}"
        )
        seeded.append(cdx_commit)

    if set_stages:
        staged = {row.slug for row in db.scalars(select(SubsystemMetadata)) if row.stage}
        for slug, stage in DEMO_STAGES.items():
            if slug not in staged:
                update_subsystem(db, slug, SubsystemUpdate(stage=stage), author)
    return seeded


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("vehicle", help="Vehicle folder to create/use under the Dashboard root")
    parser.add_argument("--author", help="Name shown on the commits (default: the Box account)")
    parser.add_argument("--set-stages", action="store_true", help="Fill in unset design stages")
    parser.add_argument("--force", action="store_true", help="Seed even if commits already exist")
    args = parser.parse_args()

    run_migrations()
    box, xrpl = get_box_service(), get_xrpl_client()
    if not xrpl.is_configured:
        print("XRPL anchoring isn't configured — commits will stay pending until it is.")
    author = box.get_current_user()
    if args.author:
        author = author.model_copy(update={"name": args.author})

    with get_sessionmaker()() as db:
        try:
            seeded = seed_demo_data(
                db,
                box,
                xrpl,
                root_folder_id=get_settings().require_dashboard_root_folder_id(),
                vehicle=args.vehicle,
                author=author,
                set_stages=args.set_stages,
                force=args.force,
            )
        except DemoDataExistsError as exc:
            raise SystemExit(str(exc)) from exc
    print(f"Seeded {len(seeded)} CDX commits.")


if __name__ == "__main__":
    main()
